### ISSUE TITLE
Crash on any command

### ISSUE THREAD

**Issue by irzhegalova** [vanheeringen-lab/gimmemotifs#103]
When I upgraded to 0.14.1 I tarted to got a bug even with gimme motifs -h

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/gimme_2/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/user/anaconda3/envs/gimme_2/lib/python3.7/site-packages/gimmemotifs/cli.py", line 179, in cli
    ).format(params["size"]),
KeyError: 'size'

What could you suggest me to do?

**Comment by simonvh** [comment]
So sorry, this is a bad upgrade on my part, I thought I had fixed this. Edit the file `~/.config/gimmemotifs`  and change `width = 200` to `size = 200`. Let me know if you still have problems after this.

**Comment by irzhegalova** [comment]
@simonvh thank you, it helped, but only a little.
still got

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/motifs.py", line 75, in motifs
    number=10000,
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 122, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 548, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 512, in matched_gc_bedfile
    min_bin_size=min_bin_size,
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 387, in gc_bin_bedfile
    create_gc_bin_index(genome, fname, min_bin_size=min_bin_size)
  File "/home/user/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 326, in create_gc_bin_index
    sizes = g.props["sizes"]["sizes"]
KeyError: 'sizes'
