### ISSUE TITLE
Gimme error -SQLlite

### ISSUE THREAD

**Issue by genomicspark** [vanheeringen-lab/gimmemotifs#110]
Hello, I recently installed gimme (by helping from HPC programmer), but I faced this issue below
Could you help me to fix this problem? Not only maelstrom has problem, the motif find with known option doesn't work
BP

$ gimme maelstrom mygenelist_quantile_normalized_lcpm_mean_center2.txt hg38 output
    2020-03-04 11:48:15,520 - INFO - Starting maelstrom
    2020-03-04 11:48:21,987 - INFO - motif scanning (counts)
    2020-03-04 11:48:21,989 - INFO - reading table
    Traceback (most recent call last):
      File "/usr/local/apps/gimmemotifs/0.14.3/bin/gimme", line 11, in <module>
        cli(sys.argv[1:])
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
        args.func(args)
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/gimmemotifs/commands/maelstrom.py", line 37, in maelstrom
        gc=gc,
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/gimmemotifs/maelstrom.py", line 311, in run_maelstrom
        gc=gc,
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/gimmemotifs/moap.py", line 122, in scan_to_table
        s.set_background(genome=genome, gc=gc, size=size)
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 726, in set_background
        with Cache(CACHE_DIR) as cache:
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/diskcache/core.py", line 442, in __init__
        sql = self._sql_retry
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/diskcache/core.py", line 634, in _sql_retry
        sql = self._sql
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/diskcache/core.py", line 629, in _sql
        return self._con.execute
      File "/usr/local/Anaconda/envs_app/GimmeMotifs/0.14.3/lib/python3.7/site-packages/diskcache/core.py", line 616, in _con
        settings = con.execute(select).fetchall()
    sqlite3.DatabaseError: database disk image is malformed

**Comment by simonvh** [comment]
Are you running on a HPC / cluster environment? There is a known bug with GimmeMotifs with concurrent jobs. Can you check if the solution mentioned in #106 fixes your issue?

**Comment by mdozmorov** [comment]
Also got a similar error happens in HPC environment. The #106 workaround didn't help. Error:
````
  File "/home/user/miniconda3/envs/gimme/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
sqlite3.OperationalError: disk I/O error
````
