### ISSUE TITLE
GimmeMotifs crashes when no motifs are found

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/gimmemotifs#118]
```
2020-05-26 10:15:00,816 - INFO - no motifs found
2020-05-26 10:15:00,816 - INFO - finished
Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/gimme/bin/gimme", line 4, in <module>
    __import__('pkg_resources').run_script('gimmemotifs==0.14.3+17.gb2ae9f6.dirty', 'gimme')
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs-0.14.3+17.gb2ae9f6.dirty-py3.6-linux-x86_64.egg/EGG-INFO/scripts/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs-0.14.3+17.gb2ae9f6.dirty-py3.6-linux-x86_64.egg/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs-0.14.3+17.gb2ae9f6.dirty-py3.6-linux-x86_64.egg/gimmemotifs/commands/motifs.py", line 97, in motifs
    denovo = read_motifs(os.path.join(args.outdir, "gimme.denovo.pfm"))
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs-0.14.3+17.gb2ae9f6.dirty-py3.6-linux-x86_64.egg/gimmemotifs/motif.py", line 1522, in read_motifs
    infile = pfmfile_location(infile)
  File "/home/simon/anaconda3/envs/gimme/lib/python3.6/site-packages/gimmemotifs-0.14.3+17.gb2ae9f6.dirty-py3.6-linux-x86_64.egg/gimmemotifs/utils.py", line 103, in pfmfile_location
    raise ValueError("Motif file {} not found".format(infile))
ValueError: Motif file testout/gimme.denovo.pfm not found
```

**Comment by adomingues** [comment]
Hi Simon,

FYI, I am still getting this error with GimmeMotifs v0.15.3.

Cheers.
