### ISSUE TITLE
Fitting RF failed, input contains NaN

### ISSUE THREAD

**Issue by ryanmboileau** [vanheeringen-lab/gimmemotifs#136]
Hi,

**Describe the bug**
Running gimme maelstrom errors out part way through with the error messages below. Seems the last files I am able to generate from this package are activity*(hypergeom | lightningclassification |  mwu.score ).score.out.tx. And an html file is not produced. There are many warnings about my scikit version (that I have mostly omitted in the logs here), but, from issues raised previously I was unable to run this software without using previous versions of it. 

**To Reproduce**
command: gimme maelstrom $pathway/$fileofinterest.bed $mygenome $outputdirectory
My bed file does not contain special characters or missing values

**Expected behavior**
HTML output with beautiful results 

**Error logs**
2020-07-30 12:16:45,804 - INFO - Starting maelstrom
2020-07-30 12:16:45,957 - INFO - motif scanning (counts)
2020-07-30 12:16:45,960 - INFO - reading table
2020-07-30 12:16:52,614 - INFO - setting threshold
2020-07-30 12:16:59,557 - INFO - creating count table
2020-07-30 12:21:48,994 - INFO - done
2020-07-30 12:21:54,421 - INFO - creating dataframe
2020-07-30 12:22:19,360 - INFO - motif scanning (scores)
2020-07-30 12:22:19,363 - INFO - reading table
2020-07-30 12:22:36,418 - INFO - creating score table (z-score, GC%)
2020-07-30 12:29:40,551 - INFO - done
2020-07-30 12:29:45,892 - INFO - creating dataframe
2020-07-30 12:31:36,255 - INFO - Fitting LightningClassification
/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
2020-07-30 14:25:33,211 - INFO - Done
2020-07-30 14:25:42,643 - INFO - Fitting MWU
2020-07-30 14:26:33,706 - INFO - Done
2020-07-30 14:26:38,950 - INFO - Fitting Hypergeom
2020-07-30 14:26:59,895 - INFO - Done
2020-07-30 14:27:08,941 - INFO - Fitting RF
2020-07-30 14:27:09,093 - WARNING - Method rf with scoring score failed
2020-07-30 14:27:09,093 - WARNING - Input contains NaN, infinity or a value too large for dtype('float32').
2020-07-30 14:27:09,093 - WARNING - Skipping
  warnings.warn(msg, category=FutureWarning)
/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
Traceback (most recent call last):
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/gimmemotifs/commands/maelstrom.py", line 37, in maelstrom
    gc=gc,
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/gimmemotifs/maelstrom.py", line 389, in run_maelstrom
    fname, score_table, outdir, method, scoring, ncpus=ncpus
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/gimmemotifs/maelstrom.py", line 79, in moap_with_table
    ncpus=ncpus,
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/gimmemotifs/moap.py", line 1067, in moap
    clf.fit(motifs, df)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/gimmemotifs/moap.py", line 771, in fit
    orc.fit(df_X.values, y)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/multiclass.py", line 239, in fit
    for i, column in enumerate(columns))
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/multiclass.py", line 79, in _fit_binary
    estimator.fit(X, y)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 295, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/utils/validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/mnt/blelloch/Boileau/conda/envs/genomepy/lib/python3.6/site-packages/sklearn/utils/validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Installation information (please complete the following information):**
Linux
# Name                    Version                   Build  Channel
bedtools                  2.29.2               hc088bd4_0    bioconda
biopython                 1.77                     pypi_0    pypi
genomepy                  0.8.4                    pypi_0    pypi
gimmemotifs               0.14.4                   pypi_0    pypi
pandas                    1.1.0                    pypi_0    pypi
pyarrow                   1.0.0                    pypi_0    pypi
pybedtools                0.8.1                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyfaidx                   0.5.9              pyh864c0ab_1    bioconda
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pysam                     0.16.0.1                 pypi_0    pypi
pysocks                   1.7.1                    py36_0  
pytest                    5.4.3                    py36_0  
python                    3.6.10               h7579374_2  
scikit-learn              0.22.1           py36hd81dba3_0  

**Additional context**

**Comment by simonvh** [comment]
I suspect this has something to do with the motifs (the `X` in the regression). The random forest will fit on the `motif.score.txt.gz` (located in your output directory). However, I have no idea what would cause this.

There's three things to try: 

1) Maybe there is a specific sequence that results in motif scores that are `NaN`? You could check `motif.score.txt.gz` and see if there are any rows that have values that are off. You can then remove that particular sequence (location) from your input.
2) Can you send me an input example that results in this error (+ genome version). Then I can try to trouble-shoot. 
3) You can try the `develop` version of GimmeMotifs. In your conda environment run `pip install git+https://github.com/vanheeringen-lab/gimmemotifs@develop`. However, I don't think we have changed any code related to this, so it's a bit of a long shot.

In the meantime, you can still retrieve HTML output (without RF) with this command:

```
gimme maelstrom $pathway/$fileofinterest.bed $mygenome $outputdirectory -m lightningclassification,mwu,hypergeom
```

I am aware of the scikit warnings, these will be fixed for the following release.

Action from my side will take some time, as I will be on holiday.

**Comment by ryanmboileau** [comment]
Hi Simon, 

Thank you for the quick response. Your suggestion to bypass the RF worked for my purposes and the results made for an interesting lab meeting. 

1) As far as I can tell, I could not find any non-numeric values in the score file and I did not find any "NaN", "NA" matches in the file. Though most values I observed are [-1, 0 +1] there were some that had extremely large scores. 

2) However, I have included the input.table.txt here with the regions I submitted. The genome is mm10. 
[input.table.txt](https://github.com/vanheeringen-lab/gimmemotifs/files/5011515/input.table.txt)\

I had some trouble setting up the dependencies and everything to run gimme in the first place- where order of installation of different required packages (such as genomepy and bedtools) and whether I used pip or conda to install were key in the process. Would pathing issues for any of the dependencies lead to this error? 

Thanks again
Ryan

**Comment by simonvh** [comment]
@ryanmboileau I've been looking into this. One of the things I noticed it that many of your input regions are very short (1bp). I figured out that `gimme maelstrom` currently does not deal very well with this. It should either warn you of the problem, or resize all regions to the same size. In any case, your current results are likely to be incorrect and/or incomplete. For now, I would suggest to set the regions to be a similar size (200bp is what we usually use) and try your analysis again.

**Comment by simonvh** [comment]
And to answer your dependency question: the optimal way is to everything via bioconda. 

```
# Only have to this once
$ conda config --add channels defaults
$ conda config --add channels bioconda
$ conda config --add channels conda-forge

# You might have to do this, it seems to fix some dependency resolution
$ conda config --set use_only_tar_bz2 True

# create env with all deps
$ conda create -n gimme gimmemotifs

# Run your analysis
$ conda activate gimme
$ gimme maelstrom [...]
```

**Comment by ryanmboileau** [comment]
Hi Simon, thanks for getting back to me. Your suggestion to increase region size for input file worked and all of the modules are now functional for my analyses. 

I originally installed gimme through conda which is what was giving me errors some months ago. Most importantly, got it to work anyway.

All the best,
Ryan
