### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tonisorg** [vanheeringen-lab/gimmemotifs#137]
**Describe the bug**
Running gimme motifs fails with some bed files with the following error:

2020-08-06 13:44:11,238 - INFO - creating background (matched GC%)
Traceback (most recent call last):
  File "/Users/elinorg/Unix/miniconda3/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/Users/elinorg/Unix/miniconda3/lib/python3.7/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/Users/elinorg/Unix/miniconda3/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 75, in motifs
    number=10000,
  File "/Users/elinorg/Unix/miniconda3/lib/python3.7/site-packages/gimmemotifs/background.py", line 122, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/Users/elinorg/Unix/miniconda3/lib/python3.7/site-packages/gimmemotifs/background.py", line 559, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/Users/elinorg/Unix/miniconda3/lib/python3.7/site-packages/gimmemotifs/background.py", line 511, in matched_gc_bedfile
    bin_count[i] += 1
IndexError: list index out of range

**To Reproduce**
Steps to reproduce the behavior: gimme motifs consensus5_clean2.bed -g hg38 consensus5_clean_hg38

**Expected behavior**
Program to start running

**Error logs**
No files created

**Installation information (please complete the following information):**
 - OS: OSX
 - Installation conda
 - Version 0.14.4

**Additional context**
It works fine with other bed files.
[consensus5_clean2.bed.zip](https://github.com/vanheeringen-lab/gimmemotifs/files/5034578/consensus5_clean2.bed.zip)

**Comment by siebrenf** [comment]
Hi @tonisorg,

Simon is on a holiday, but I can give you a quick fix :)

in this file: `/Users/elinorg/Unix/miniconda3/lib/python3.7/site-packages/gimmemotifs/background.py` on line 510 you can find the following code:
```
for i in range(rest):
```
change this to 
```
for i in range(min(rest, len(bin_count))):
```

**Comment by tonisorg** [comment]
Thanks a lot for a quick response! It is working now!

Best,
Tonis
