### ISSUE TITLE
Gimme motifs command costum background

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/gimmemotifs#140]
**Describe the bug**
Trying to supply a costum background in a bed format for denovo motif analysis, causes it to crash.

head costum background bed file:

```
1	882858	883358
1	971241	971741
1	980009	980509
1	1003405	1003905
1	1006840	1007340
1	1021397	1021897
1	1025675	1026175
1	1143917	1144417
1	1163003	1163503
1	1176991	1177491
```

head input file:

```
1	995733	996233
1	3685245	3685745
1	6581859	6582359
1	6824626	6825126
1	7555867	7556367
1	8153625	8154125
1	9331490	9331990
1	9665271	9665771
1	11139718	11140218
1	11495922	11496422
```

code trying to run gimme motifs with a specific background:
```
gimme motifs   \
/home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/differential_TP63_regions_LSC.bed   \
/home/jsmits/gimme_LSC_TP63_bg_output   \
-b /home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/non-differential_TP63_regions.bed  \
--denovo   \
-g /home/jsmits/tools/GRCh38.p13/GRCh38.p13.fa   \
-N 8
```

**To Reproduce**
Run a gimme motif command with a custom bedfile as a background

**Expected behavior**
Accepting bed files as a background to compare with.

**Error logs**
```
2020-08-11 11:03:29,539 - INFO - starting full motif analysis
2020-08-11 11:03:29,602 - INFO - using size of 200, set size to 0 to use original region size
2020-08-11 11:03:29,603 - INFO - preparing input from BED
2020-08-11 11:03:29,895 - INFO - Copying custom background file /home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/non-differential_TP63_regions.bed to /home/jsmits/gimme_LSC_TP63_bg/intermediate/prediction.bg.fa.
Traceback (most recent call last):
  File "/home/jsmits/anaconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 112, in motifs
    "size": args.size,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 609, in gimme_motifs
    params.get("custom_background", None),
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 316, in create_backgrounds
    custom_background=custom_background,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 259, in create_background
    f = Fasta(bg_file)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/fasta.py", line 25, in __init__
    raise IOError("Not a valid FASTA file")
OSError: Not a valid FASTA file

```
**Installation information (please complete the following information):**
```
 - OS: mb07
 - conda (updated with pip)
 - gimmemotifs               0.14.4+78.g5555099          pypi_0    pypi
```

**Comment by JGASmits** [comment]
Possible linked to https://github.com/vanheeringen-lab/gimmemotifs/issues/139 ?

**Comment by JGASmits** [comment]
Sadly, even with the fastq input it crashes after a while :(
```
2020-08-11 15:10:34,343 - INFO - starting full motif analysis
2020-08-11 15:10:34,392 - INFO - using size of 200, set size to 0 to use original region size
2020-08-11 15:10:34,392 - INFO - preparing input from BED
2020-08-11 15:10:35,548 - INFO - Copying custom background file /home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/non-differential_TP63_regions.fasta to /home/jsmits/gimme_LSC_TP63_bg/intermediate/prediction.bg.fa.
2020-08-11 15:10:36,909 - WARNING - The custom background file /home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/non-differential_TP63_regions.fasta contains sequences with a median size of 500.0, while GimmeMotifs predicts motifs in sequences of size 200. This will influence the statistics! It is recommended to use background sequences of the same size.
2020-08-11 15:10:37,144 - INFO - Copying custom background file /home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/non-differential_TP63_regions.fasta to /home/jsmits/gimme_LSC_TP63_bg/intermediate/bg.custom.fa.
2020-08-11 15:10:38,457 - WARNING - The custom background file /home/jsmits/Epithelial_fate_KC_LSC/Python_analysis/2020-08-04/non-differential_TP63_regions.fasta contains sequences with a median size of 500.0, while GimmeMotifs predicts motifs in sequences of size 200. This will influence the statistics! It is recommended to use background sequences of the same size.
2020-08-11 15:10:38,926 - INFO - starting motif prediction (xl)
2020-08-11 15:10:38,927 - INFO - tools: MEME, BioProspector, Homer
2020-08-11 15:10:40,497 - INFO - all jobs submitted
2020-08-11 15:11:02,586 - INFO - BioProspector_width_6 finished, found 5 motifs
2020-08-11 15:11:04,329 - INFO - BioProspector_width_12 finished, found 5 motifs
2020-08-11 15:11:05,781 - INFO - BioProspector_width_8 finished, found 5 motifs
2020-08-11 15:11:05,874 - INFO - BioProspector_width_10 finished, found 5 motifs
2020-08-11 15:11:06,095 - INFO - BioProspector_width_18 finished, found 5 motifs
2020-08-11 15:11:14,394 - INFO - BioProspector_width_14 finished, found 5 motifs
2020-08-11 15:11:16,332 - INFO - BioProspector_width_20 finished, found 5 motifs
2020-08-11 15:11:16,552 - INFO - BioProspector_width_16 finished, found 5 motifs
2020-08-11 15:11:26,637 - INFO - Homer_width_6 finished, found 5 motifs
2020-08-11 15:11:45,350 - INFO - Homer_width_8 finished, found 5 motifs
2020-08-11 15:12:15,314 - INFO - Homer_width_10 finished, found 5 motifs
2020-08-11 15:15:37,672 - INFO - Homer_width_12 finished, found 5 motifs
2020-08-11 15:21:29,642 - INFO - MEME_width_16 finished, found 10 motifs
2020-08-11 15:21:49,324 - INFO - MEME_width_14 finished, found 10 motifs
2020-08-11 15:21:49,498 - INFO - MEME_width_18 finished, found 10 motifs
2020-08-11 15:22:30,357 - INFO - MEME_width_6 finished, found 10 motifs
2020-08-11 15:23:00,945 - INFO - MEME_width_8 finished, found 10 motifs
2020-08-11 15:23:34,698 - INFO - MEME_width_20 finished, found 10 motifs
2020-08-11 15:24:42,069 - INFO - MEME_width_12 finished, found 10 motifs
2020-08-11 15:25:05,562 - INFO - MEME_width_10 finished, found 10 motifs
2020-08-11 15:28:05,338 - INFO - Homer_width_14 finished, found 5 motifs
2020-08-11 15:37:18,594 - INFO - Homer_width_16 finished, found 5 motifs
2020-08-11 15:44:07,476 - INFO - Homer_width_18 finished, found 5 motifs
2020-08-11 16:04:09,259 - INFO - Homer_width_20 finished, found 5 motifs
2020-08-11 16:05:33,651 - INFO - predicted 160 motifs
2020-08-11 16:05:33,683 - INFO - 1 motifs are significant
Traceback (most recent call last):
  File "/home/jsmits/anaconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 112, in motifs
    "size": args.size,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 662, in gimme_motifs
    result.stats,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 462, in best_motif_in_cluster
    fg_file=fg_fa, bg_file=bg_fa, motifs=clustered_motifs, genome=genome
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/stats.py", line 226, in calc_stats
    gc=gc,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/stats.py", line 133, in calc_stats_iterator
    fg_file, motifs, ncpus=ncpus, genome=genome, zscore=zscore, gc=gc
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 338, in scan_to_best_match
    s = Scanner(ncpus=ncpus)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 551, in __init__
    self.pool = mp.Pool(processes=self.ncpus)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by JGASmits** [comment]
I've tried rerunning it with only 4 cores, and this changes the error, it is also weird that the ammount of 'significant motifs' it finds varies between tries (between 1, 2 in this example and I've also seen it find 6 when i tried to rerun it with exactly the same settings):
`2020-08-19 16:07:06,950 - INFO - predicted 160 motifs
2020-08-19 16:07:06,983 - INFO - 2 motifs are significant
2020-08-19 16:07:06,995 - INFO - clustering 2 motifs.
Traceback (most recent call last):
  File "/home/jsmits/anaconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 112, in motifs
    "size": args.size,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 662, in gimme_motifs
    result.stats,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/denovo.py", line 462, in best_motif_in_cluster
    fg_file=fg_fa, bg_file=bg_fa, motifs=clustered_motifs, genome=genome
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/stats.py", line 226, in calc_stats
    gc=gc,
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/stats.py", line 119, in calc_stats_iterator
    s.set_motifs(all_motifs)
  File "/home/jsmits/anaconda3/envs/gimme/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 582, in set_motifs
    motifs[0].to_pwm()
IndexError: list index out of range`

**Comment by simonvh** [comment]
@JGASmits background needs to be the same region size as your input, in FASTA format. You can change your custom background BED file to fasta with [`bedtools getfasta`](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html).
