### ISSUE TITLE
Setting the Region size to use for motif prediction as 0 or 2000 reported 'ValueError: a must be greater than 0 unless no samples are taken'

### ISSUE THREAD

**Issue by echoduan** [vanheeringen-lab/gimmemotifs#146]
Hello,

    I have installed the GimmeMotifs successfully. It was running normally when setting region size (-s) as 200 (default) or 400.
2020-10-09 04:30:18,410 - INFO - creating background (matched GC%)
2020-10-09 04:32:13,478 - INFO - starting full motif analysis
2020-10-09 04:32:13,479 - INFO - using size of 200, set size to 0 to use original region size
2020-10-09 04:32:13,479 - INFO - preparing input from BED
2020-10-09 04:34:10,734 - INFO - starting motif prediction (xl)
2020-10-09 04:34:10,734 - INFO - tools: MEME, BioProspector, Homer
............

    However, the bug will be reported when changing the region size (-s) into 2000 or 0
2020-10-09 04:29:09,731 - INFO - creating background (matched GC%)
Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/envs/py37/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/ec2-user/anaconda2/envs/py37/lib/python3.7/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/home/ec2-user/anaconda2/envs/py37/lib/python3.7/site-packages/gimmemotifs/commands/motifs.py", line 94, in motifs
    number=10000,
  File "/home/ec2-user/anaconda2/envs/py37/lib/python3.7/site-packages/gimmemotifs/background.py", line 120, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/home/ec2-user/anaconda2/envs/py37/lib/python3.7/site-packages/gimmemotifs/background.py", line 564, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/home/ec2-user/anaconda2/envs/py37/lib/python3.7/site-packages/gimmemotifs/background.py", line 538, in matched_gc_bedfile
    df.loc[df["bin"] == b, ["chrom", "start", "end"]].sample(n).to_csv(
  File "/home/ec2-user/anaconda2/envs/py37/lib/python3.7/site-packages/pandas/core/generic.py", line 4993, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 894, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

And I want to predict the Motif sequence relying on the input original regions or broad regions. Could you have any suggestions about this issue?

**Comment by simonvh** [comment]
Can you try to install the fix in your conda environment?

```
pip install git+https://github.com/vanheeringen-lab/gimmemotifs@f3d08fa
```

Could you check if this fixed your issue?

**Comment by jos4uke** [comment]
Hi 

I also have encountered this issue using `gimme motifs` on my fasta file

**Step to reproduce:**

```bash
SEQDIR=seq
ZONES=(zone1 zone2 zone3 zone4)
ZONE_SEQS=(cds.ranges.zone1.flank.seqs.fa  cds.ranges.zone2.flank.seqs.fa  cds.ranges.zone3.flank.seqs.fa  cds.ranges.zone4.flank.seqs.fa)
OUTDIR=gimmemotifs
THREADS=12
#### gimme motifs 
MOTIFS_DB=JASPAR2020_plants 
REF_GENOME=my_genome.fa

ZONE_SEQ=$SEQDIR/${ZONE_SEQS[$SLURM_ARRAY_TASK_ID]}
ZONE=${ZONES[$SLURM_ARRAY_TASK_ID]}
OUTDIR_MOTIFS=${OUTDIR}/${ZONE}.motifs
echo "### zone seq file: ${ZONE_SEQ}"
echo "### zone: ${ZONE}"
echo "### output directory: ${OUTDIR_MOTIFS}"

gimme motifs ${ZONE_SEQ} ${OUTDIR_MOTIFS} \
	-g ${REF_GENOME} \
	--background gc \
	-p ${MOTIFS_DB} \
	--analysis xl \
	--keepintermediate \
	--size 1000 \
	-N ${THREADS}

```


**Error Logs:**

```bash
2021-01-13 21:49:38,902 - WARNING - size parameter will be ignored for FASTA input
2021-01-13 21:49:38,903 - INFO - creating background (matched GC%)
Traceback (most recent call last):
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/commands/motifs.py", line 87, in motifs
    create_background_file(
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/background.py", line 120, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/background.py", line 564, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/background.py", line 538, in matched_gc_bedfile
    df.loc[df["bin"] == b, ["chrom", "start", "end"]].sample(n).to_csv(
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/generic.py", line 5345, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
``` 

**Installation information:**
 - OS: Linux node7 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux 
 - Installation: `bash mamba create -n gimmemotifs python=3 gimmemotifs`
 - Versions:
   -   python                    3.8.6           hffdb5ce_4_cpython    conda-forge
   -  gimmemotifs               0.15.2           py38h0213d0e_0    bioconda

**Comment by simonvh** [comment]
@jos4uke I thought this error was fixed, apparently it is not. I think this may have to do with using the `-s` parameter in combination with FASTA files. It should (as the log message indicated) currently be ignored, but given the error it seems that that's not the case. I'll have a look. 

For now, with FASTA sequences, I would suggest to create the FASTA files with the size that you want to use and then to not specify the `-s` parameter.

**Comment by jos4uke** [comment]
Hi @simonvh 

thanks for your answer. I will follow your recommendation.

Best

**Comment by jos4uke** [comment]
Hi @simonvh 

just a remark, when I switched background to random, the `-s` parameter is ignored as you expected.
It seems using `--background gc`, defined as default, did not have the same behaviour.

Best
