### ISSUE TITLE
KeyError: 'params' popping up during gimme motifs command run

### ISSUE THREAD

**Issue by sufyazi** [vanheeringen-lab/gimmemotifs#157]
**Describe the bug**
So every time I run gimme motifs (the only command I've run so far) on my system, although the run will finish successfully, I have to manually CRTL+C and quit my terminal because the program will seem to be stuck at trying to resolve this KeyError.

**To Reproduce**
I run a standard `gimme motifs` command:
```
gimme motifs INPUT.narrowPeak OUTPUTPATH -g GENOME.fa
```

**Expected behavior**
As I have never run gimme motifs without seeing these errors pop up I'm not sure what I expect it to look. But here's the output lines printed as the run is going:

<img width="1263" alt="Screen Shot 2020-12-03 at 9 15 35 pm" src="https://user-images.githubusercontent.com/15644815/101004817-c7f46480-35b4-11eb-819e-c363f3acee39.png">

and as time passes, I'll see motifs being called and found and some `matplotlib` lines about building the font cache

<img width="1263" alt="Screen Shot 2020-12-03 at 9 15 51 pm" src="https://user-images.githubusercontent.com/15644815/101005518-fb36f380-35b4-11eb-8d82-deade6ccdf06.png">

**Error logs**
And usually the KeyError will pop up after these repeated 'matplotlib building cache' lines, with these exact lines:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/denovo.py", line 51, in <module>
    from gimmemotifs.stats import calc_stats, rank_motifs, write_stats
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/stats.py", line 10, in <module>
    from gimmemotifs.scanner import scan_to_best_match, Scanner
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 55, in <module>
    config = MotifConfig()
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/config.py", line 95, in __init__
    self._upgrade_config()
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/config.py", line 98, in _upgrade_config
    if "width" in self.config["params"]:
  File "/Users/sufyazi/opt/anaconda3/envs/gimme/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'params'
```
And usually these would appear back to back, which to me a non-programmer, looks like it's stuck in a loop of some sort.

<img width="1253" alt="Screen Shot 2020-12-03 at 10 10 19 pm" src="https://user-images.githubusercontent.com/15644815/101006608-4e10ab00-35b5-11eb-9a0f-8da1c484404c.png">

However after a while, I will always see these lines, indicating that the run actually did run, and has finished.
<img width="1055" alt="Screen Shot 2020-12-03 at 9 59 34 pm" src="https://user-images.githubusercontent.com/15644815/101007569-9334dd00-35b5-11eb-8fb9-fb8ec1780a67.png">

But as you can see in the last line, the CPU is still at work and the whole traceback lines will appear back to back, until I manually suspend the process and/or exit the terminal.

Later I would check the output files and everything looks like it has worked. So I am not sure what exactly is happening, seeing that the program actually did work despite the error messages. 

**Installation information (please complete the following information):**
 - OS: MacOS BigSur 11.0.1
 - Installation conda (pypi)
 - Version gimmemotifs 0.15.2+2.g2d3b70b

**Additional context**
After I manually `CTRL+C`, I usually get this warning, with xxxx being digits that usually differs between runs.

```
There appear to be xxxx leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d
```

**Comment by simonvh** [comment]
Can you try the following:

1) delete the GimmeMotifs config file

```
rm ~/.config/gimmemotifs/gimmemotifs.cfg
```

2) Run gimme motifs without any arguments

```
gimme motifs
```

(it should rebuild the config)

3) Run your analysis as normal.

**Comment by sufyazi** [comment]
Hi, I followed your instruction but in the middle of the run the keyError messages still came up. The output came out as expected anyway, so I'm not sure what's causing this.
