### ISSUE TITLE
genome installation problem

### ISSUE THREAD

**Issue by fgualdr** [vanheeringen-lab/gimmemotifs#159]
Hi,

I am trying to freshly install genome but an error with genome-you comes out:
Don't know what to do as the folder I create to store genomes is completely empty to start with

 genomepy install mm10 --annotation
Downloading genome from UCSC.
Target URL: http://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/chromFa.tar.gz...
Genome download successful, starting post processing...
Traceback (most recent call last):
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/bin/genomepy", line 10, in <module>
    sys.exit(cli())
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/genomepy/cli.py", line 221, in install
    genomepy.install_genome(
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/genomepy/functions.py", line 305, in install_genome
    p.download_genome(
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/genomepy/provider.py", line 303, in download_genome
    shutil.move(src, dst)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/tempfile.py", line 827, in __exit__
    self.cleanup()
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/tempfile.py", line 831, in cleanup
    self._rmtree(self.name)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/shutil.py", line 719, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/shutil.py", line 717, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/hpcnfs/data/GN2/fgualdrini/.local/share/genomes/mm10/tmp214g9nnb'

**Comment by simonvh** [comment]
I hope this was solved in the meantime. In any case, if you encounter any further problems with genomepy, please post an issue here: https://github.com/vanheeringen-lab/genomepy/issues.
