### ISSUE TITLE
gimme motifs with FASTA

### ISSUE THREAD

**Issue by fgualdr** [vanheeringen-lab/gimmemotifs#160]
Hi,

I am having several issues with gimme motif.
I freshly re-install all together with new genomes using genome-you as indicated.
I generated fasta files for both sample and background using bedroll and the .fa file obtained with genomepy. 
The size of background and samples are both 151bp

I run the script as follow:
gimme motifs $FOLDER/temp.fa $FOLDEROUT/ --background $BG_FOLDER/BG.fa -p $pfm_file --known

I got the following error:

Nevertheless I get the following error:

2020-12-13 19:00:29,932 - WARNING - size parameter will be ignored for FASTA input
2020-12-13 19:01:05,856 - INFO - skipping de novo
2020-12-13 19:01:05,876 - INFO - creating motif scan tables
Traceback (most recent call last):
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/commands/motifs.py", line 186, in motifs
    scan_to_file(
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 383, in scan_to_file
    for line in command_scan(
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 324, in command_scan
    for row in it:
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 221, in scan_score_table
    for i, scores in enumerate(result_it):
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 1010, in best_score
    for matches in self.scan(seqs, 1, scan_rc, zscore=zscore, gc=gc):
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 1078, in scan
    self.set_meanstd(gc=gc)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 715, in set_meanstd
    self.set_background(gc=gc)
  File "/hpcnfs/data/GN2/fgualdrini/.conda/envs/gimme/lib/python3.8/site-packages/gimmemotifs/scanner.py", line 839, in set_background
    raise ValueError("Need either genome or filename for background.")
ValueError: Need either genome or filename for background.

**Comment by simonvh** [comment]
Sorry, this took a long while. This is now fixed. By default `gimme motifs` transforms motifs to z-score and takes G% of the sequences into account. However, a genome is necessary to do this. Now, when you supply a background fasta, z-score and GC% correction are turned off, and the supplied background is used.
