### ISSUE TITLE
gimme motifs error: creating statistics report crashed with KeyError: 'Factor'

### ISSUE THREAD

**Issue by jos4uke** [vanheeringen-lab/gimmemotifs#170]
Hi @simonvh 

I ran gimme motifs after several  attempts and add-ons to my script you suggested me earlier.
But still I was not able to complete the full analysis. It crashed trying to generate the statistics report throwing a `KeyError: 'Factor'`.

Can you help please?

@jos4uke

**To Reproduce**

```bash
SEQDIR=seq
ZONES=(zone1 zone2 zone3 zone4)
ZONE_SEQS=(cds.ranges.zone1.flank.seqs.fa  cds.ranges.zone2.flank.seqs.fa  cds.ranges.zone3.flank.seqs.fa  cds.ranges.zone4.flank.seqs.fa)
OUTDIR=gimmemotifs
THREADS=12
#### gimme motifs 
MOTIFS_DB=JASPAR2020_plants 
REF_GENOME=my_genome.fa

# run information
ZONE_SEQ=$SEQDIR/${ZONE_SEQS[$SLURM_ARRAY_TASK_ID]}
ZONE=${ZONES[$SLURM_ARRAY_TASK_ID]}
OUTDIR_MOTIFS=${OUTDIR}/${ZONE}.motifs.random_bg
echo "### zone seq file: ${ZONE_SEQ}"
echo "### zone: ${ZONE}"
echo "### output directory: ${OUTDIR_MOTIFS}"
mkdir -p $OUTDIR_MOTIFS
echo "### create output directory: done"

# setup new cache 
# cache corruption on cluster workaround: https://gimmemotifs.readthedocs.io/en/master/faq.html#sqlite-error-when-running-on-a-cluster
NEW_CACHE=$OUTDIR_MOTIFS/cache
mkdir -p $NEW_CACHE
if [ -z $XDG_CACHE_HOME ]; then
    XDG_CACHE_HOME=$HOME/.cache
fi
cp -r $XDG_CACHE_HOME/gimmemotifs $NEW_CACHE/
export XDG_CACHE_HOME=$NEW_CACHE
echo '### new cache: Using $XDG_CACHE_HOME for cache'

gimme motifs ${ZONE_SEQ} ${OUTDIR_MOTIFS} \
	-g ${REF_GENOME} \
	--background random \
	-p ${MOTIFS_DB} \
	--analysis xl \
	--keepintermediate \
	--size 1000 \
	-N ${THREADS}

```

**Error logs**

```bash
2021-01-14 21:23:38,498 - INFO - creating background (random)
2021-01-14 21:23:55,607 - INFO - starting full motif analysis
2021-01-14 21:23:55,630 - INFO - using original size
2021-01-14 21:23:55,630 - INFO - preparing input from FASTA
2021-01-14 21:23:55,630 - INFO - preparing input (FASTA)
2021-01-14 21:24:27,487 - INFO - starting motif prediction (xl)
2021-01-14 21:24:27,488 - INFO - tools: MEME, BioProspector, Homer
2021-01-14 21:24:28,266 - INFO - all jobs submitted
2021-01-14 21:24:40,746 - INFO - Homer_width_6 finished, found 5 motifs
2021-01-14 21:24:44,046 - INFO - Homer_width_8 finished, found 5 motifs
2021-01-14 21:25:29,599 - INFO - Homer_width_10 finished, found 5 motifs
2021-01-14 21:27:04,055 - INFO - Homer_width_12 finished, found 5 motifs
2021-01-14 21:29:09,013 - INFO - BioProspector_width_6 finished, found 5 motifs
2021-01-14 21:29:09,462 - INFO - MEME_width_6 finished, found 0 motifs
2021-01-14 21:29:09,644 - INFO - MEME_width_8 finished, found 0 motifs
2021-01-14 21:29:09,808 - INFO - MEME_width_10 finished, found 0 motifs
2021-01-14 21:29:09,966 - INFO - MEME_width_12 finished, found 0 motifs
2021-01-14 21:29:10,135 - INFO - MEME_width_14 finished, found 0 motifs
2021-01-14 21:29:10,310 - INFO - MEME_width_16 finished, found 0 motifs
2021-01-14 21:29:10,473 - INFO - MEME_width_18 finished, found 0 motifs
2021-01-14 21:29:10,634 - INFO - MEME_width_20 finished, found 0 motifs
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
2021-01-14 21:29:11,185 - INFO - using 14000 sequences
2021-01-14 21:29:11,186 - INFO - Creating index for genomic GC frequencies.
2021-01-14 21:29:31,371 - INFO - Homer_width_14 finished, found 5 motifs
2021-01-14 21:29:33,975 - INFO - BioProspector_width_8 finished, found 5 motifs
2021-01-14 21:29:56,546 - INFO - BioProspector_width_10 finished, found 5 motifs
2021-01-14 21:30:20,797 - INFO - BioProspector_width_12 finished, found 5 motifs
2021-01-14 21:30:36,001 - INFO - BioProspector_width_14 finished, found 5 motifs
2021-01-14 21:30:58,691 - INFO - BioProspector_width_16 finished, found 5 motifs
2021-01-14 21:31:15,074 - INFO - BioProspector_width_20 finished, found 5 motifs
2021-01-14 21:31:20,170 - INFO - BioProspector_width_18 finished, found 5 motifs
2021-01-14 21:33:42,374 - INFO - Homer_width_16 finished, found 5 motifs
2021-01-14 21:38:07,963 - INFO - Homer_width_18 finished, found 5 motifs
2021-01-14 21:45:17,678 - INFO - Homer_width_20 finished, found 5 motifs
2021-01-14 21:45:58,723 - INFO - predicted 80 motifs
2021-01-14 21:45:58,734 - INFO - 78 motifs are significant
2021-01-14 21:45:59,182 - INFO - clustering 78 motifs.
2021-01-14 21:47:30,038 - INFO - creating de novo reports
2021-01-14 21:48:25,695 - INFO - finished
2021-01-14 21:48:25,695 - INFO - output dir: gimmemotifs/zone4.motifs.random_bg
2021-01-14 21:48:25,695 - INFO - de novo report: gimmemotifs/zone4.motifs.random_bg/gimme.denovo.html
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
2021-01-14 21:49:00,534 - INFO - creating motif scan tables
2021-01-14 21:49:08,296 - INFO - using 14000 sequences
2021-01-14 22:07:59,320 - WARNING - Using 0.75-0.80
2021-01-14 22:09:18,919 - WARNING - Using 0.75-0.80
2021-01-14 22:11:20,017 - INFO - calculating stats
2021-01-14 22:12:10,075 - INFO - selecting non-redundant motifs
2021-01-14 22:12:24,993 - INFO - selected 22 non-redundant motifs: ROC AUC 0.911, PR AUC 0.825
2021-01-14 22:12:25,912 - INFO - determining FPR-based threshold
2021-01-14 22:12:27,610 - WARNING - Using 0.75-0.80
2021-01-14 22:12:28,888 - INFO - determining FPR-based threshold
2021-01-14 22:12:30,563 - WARNING - Using 0.75-0.80
2021-01-14 22:12:31,832 - INFO - determining FPR-based threshold
2021-01-14 22:12:33,709 - WARNING - Using 0.75-0.80
2021-01-14 22:12:35,006 - INFO - determining FPR-based threshold
2021-01-14 22:12:36,524 - WARNING - Using 0.75-0.80
2021-01-14 22:12:37,791 - INFO - determining FPR-based threshold
2021-01-14 22:12:39,454 - WARNING - Using 0.75-0.80
2021-01-14 22:12:40,751 - INFO - determining FPR-based threshold
2021-01-14 22:12:42,402 - WARNING - Using 0.75-0.80
2021-01-14 22:12:43,672 - INFO - determining FPR-based threshold
2021-01-14 22:12:45,426 - WARNING - Using 0.75-0.80
2021-01-14 22:12:46,731 - INFO - determining FPR-based threshold
2021-01-14 22:12:48,417 - WARNING - Using 0.75-0.80
2021-01-14 22:12:49,749 - INFO - determining FPR-based threshold
2021-01-14 22:12:51,326 - WARNING - Using 0.75-0.80
2021-01-14 22:12:52,590 - INFO - determining FPR-based threshold
2021-01-14 22:12:54,093 - WARNING - Using 0.75-0.80
2021-01-14 22:12:55,326 - INFO - determining FPR-based threshold
2021-01-14 22:12:56,876 - WARNING - Using 0.75-0.80
2021-01-14 22:12:58,120 - INFO - determining FPR-based threshold
2021-01-14 22:12:59,847 - WARNING - Using 0.75-0.80
2021-01-14 22:13:01,128 - INFO - determining FPR-based threshold
2021-01-14 22:13:02,699 - WARNING - Using 0.75-0.80
2021-01-14 22:13:03,971 - INFO - determining FPR-based threshold
2021-01-14 22:13:05,564 - WARNING - Using 0.75-0.80
2021-01-14 22:13:06,833 - INFO - determining FPR-based threshold
2021-01-14 22:13:08,370 - WARNING - Using 0.75-0.80
2021-01-14 22:13:09,638 - INFO - determining FPR-based threshold
2021-01-14 22:13:11,260 - WARNING - Using 0.75-0.80
2021-01-14 22:13:12,544 - INFO - determining FPR-based threshold
2021-01-14 22:13:14,243 - WARNING - Using 0.75-0.80
2021-01-14 22:13:15,549 - INFO - determining FPR-based threshold
2021-01-14 22:13:17,128 - WARNING - Using 0.75-0.80
2021-01-14 22:13:18,409 - INFO - determining FPR-based threshold
2021-01-14 22:13:20,032 - WARNING - Using 0.75-0.80
2021-01-14 22:13:21,306 - INFO - determining FPR-based threshold
2021-01-14 22:13:22,963 - WARNING - Using 0.75-0.80
2021-01-14 22:13:24,234 - INFO - determining FPR-based threshold
2021-01-14 22:13:25,861 - WARNING - Using 0.75-0.80
2021-01-14 22:13:27,139 - INFO - determining FPR-based threshold
2021-01-14 22:13:28,691 - WARNING - Using 0.75-0.80
2021-01-14 22:13:29,109 - INFO - creating statistics report
Traceback (most recent call last):
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Factor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/cli.py", line 661, in cli
    args.func(args)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/commands/motifs.py", line 265, in motifs
    roc_html_report(
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/report.py", line 970, in roc_html_report
    0, "factors", motif_to_factor_series(df.index, pfmfile=pfmfile, motifs=motifs)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/report.py", line 816, in motif_to_factor_series
    factors = [motifs[motif].format_factors(html=True) for motif in series]
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/report.py", line 816, in <listcomp>
    factors = [motifs[motif].format_factors(html=True) for motif in series]
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/motif.py", line 1332, in format_factors
    fcount = Counter([x.upper() for x in self.factor_info["Factor"]])
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/series.py", line 824, in __getitem__
    return self._get_value(key)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/series.py", line 932, in _get_value
    loc = self.index.get_loc(label)
  File "/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'Factor'

```

***Installation information:**
 - OS: Linux node7 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux 
 - Installation: `bash mamba create -n gimmemotifs python=3 gimmemotifs`
 - Versions:
   -   python                    3.8.6           hffdb5ce_4_cpython    conda-forge
   -  gimmemotifs               0.15.2           py38h0213d0e_0    bioconda

**Additional context**

 Here is the config file content:

```bash
# ~/.config/gimmemotifs/gimmemotifs.cfg
[main]
bg = bg
template_dir = templates
score_dir = score_dists
gene_dir = genes
motif_databases = motif_databases
tools = included_tools/

[params]
fraction = 0.2
use_strand = False
abs_max = 5000
analysis = xl
enrichment = 1.5
size = 200
lsize = 500
background = gc,random
cluster_threshold = 0.95
scan_cutoff = 0.9
available_tools = MDmodule,MEME,MEMEW,Weeder,GADEM,MotifSampler,Trawler,Improbizer,BioProspector,Posmo,ChIPMunk,AMD,HMS,Homer,XXmotif,ProSampler,DiNAMO
tools = MEME,BioProspector,Homer
pvalue = 0.001
max_time = -1
ncpus = 12
motif_db = JASPAR2020_plants.pfm
use_cache = False

[YAMDA]
bin = run_em.py
dir = included_tools/

[DiNAMO]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/dinamo
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[RPMCMC]
bin = multi_motif_finder
dir = included_tools/

[ProSampler]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/ProSampler
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[AMD]
bin = AMD.bin
dir = included_tools/

[MEME]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/meme
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[DREME]
bin = dreme-py3
dir = included_tools/

[MEMEW]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/meme
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[MDmodule]
bin = MDmodule
dir = included_tools/

[Improbizer]
bin = ameme
dir = included_tools/

[MotifSampler]
bin = MotifSampler
dir = included_tools/

[GADEM]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/gadem
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[Trawler]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/trawler
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[Weeder]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/weeder2
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[BioProspector]
bin = BioProspector
dir = included_tools/

[ChIPMunk]
bin = ChIPMunk.sh
dir = included_tools/ChIPMunk

[Homer]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/homer2
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[XXmotif]
bin = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin/XXmotif
dir = /opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/bin

[Posmo]
bin = posmo
dir = included_tools/

[HMS]
bin = hms
dir = included_tools/HMS

```.

**Comment by simonvh** [comment]
Hmm. I don't know what the underlying cause of this error is, but can you try changing line 1332 of `/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/gimmemotifs/motif.py`
from 
```
fcount = Counter([x.upper() for x in self.factor_info["Factor"]])
```
to
```
fcount = Counter([x.upper() for x in self.factor_info.get("Factor", "")])
```

If that works I'll add it to the next bugfix release.

**Comment by jos4uke** [comment]
Hi @simonvh 

I updated the code as you recommended, and I got the final report `gimme.motifs.html`.

Here is the log:

```bash
2021-01-15 10:07:50,709 - INFO - creating background (random)
2021-01-15 10:08:08,670 - INFO - skipping de novo
2021-01-15 10:08:08,671 - INFO - creating motif scan tables
2021-01-15 10:08:17,602 - INFO - using 14000 sequences
2021-01-15 10:08:17,603 - INFO - Creating index for genomic GC frequencies.
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
2021-01-15 10:26:11,048 - WARNING - Using 0.75-0.80
2021-01-15 10:27:38,182 - WARNING - Using 0.75-0.80
2021-01-15 10:29:36,285 - INFO - calculating stats
2021-01-15 10:30:24,956 - INFO - selecting non-redundant motifs
2021-01-15 10:30:31,031 - INFO - selected 10 non-redundant motifs: ROC AUC 0.940, PR AUC 0.882
2021-01-15 10:30:31,905 - INFO - determining FPR-based threshold
2021-01-15 10:30:33,615 - WARNING - Using 0.75-0.80
2021-01-15 10:30:34,907 - INFO - determining FPR-based threshold
2021-01-15 10:30:36,917 - WARNING - Using 0.75-0.80
2021-01-15 10:30:38,371 - INFO - determining FPR-based threshold
2021-01-15 10:30:40,168 - WARNING - Using 0.75-0.80
2021-01-15 10:30:41,453 - INFO - determining FPR-based threshold
2021-01-15 10:30:43,179 - WARNING - Using 0.75-0.80
2021-01-15 10:30:44,485 - INFO - determining FPR-based threshold
2021-01-15 10:30:46,188 - WARNING - Using 0.75-0.80
2021-01-15 10:30:47,492 - INFO - determining FPR-based threshold
2021-01-15 10:30:49,187 - WARNING - Using 0.75-0.80
2021-01-15 10:30:50,613 - INFO - determining FPR-based threshold
2021-01-15 10:30:52,342 - WARNING - Using 0.75-0.80
2021-01-15 10:30:53,682 - INFO - determining FPR-based threshold
2021-01-15 10:30:55,352 - WARNING - Using 0.75-0.80
2021-01-15 10:30:56,642 - INFO - determining FPR-based threshold
2021-01-15 10:30:58,510 - WARNING - Using 0.75-0.80
2021-01-15 10:30:59,764 - INFO - determining FPR-based threshold
2021-01-15 10:31:01,410 - WARNING - Using 0.75-0.80
2021-01-15 10:31:01,825 - INFO - creating statistics report
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/arraylike.py:274: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/io/formats/style.py:1268: RuntimeWarning: invalid value encountered in double_scalars
  norm = colors.Normalize(smin - (rng * low), smax + (rng * high))
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/arraylike.py:274: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/io/formats/style.py:1268: RuntimeWarning: invalid value encountered in double_scalars
  norm = colors.Normalize(smin - (rng * low), smax + (rng * high))
2021-01-15 10:33:30,057 - INFO - gimme motifs final report: gimmemotifs/zone2.random_bg.debug/gimme.motifs.html

```

As you may see, there are some warnings about log10 division by 0, but they don't seem to affect the report creation.

thanks a lot for your help

Best

**Comment by jos4uke** [comment]
@simonvh 

I just checked my script again and I added `--known` to the command line.
So the results are related to this run.
I will run again the script, removing this option, as I did run previously before the error and tell you if everything is ok.

**Comment by jos4uke** [comment]
@simonvh 

I confirmed you that the trick fixed the error also on a full motif analysis.

thank you very much

Best

Here is the log:

```bash
2021-01-15 11:00:18,736 - INFO - creating background (random)
2021-01-15 11:00:36,717 - INFO - starting full motif analysis
2021-01-15 11:00:36,744 - INFO - using original size
2021-01-15 11:00:36,744 - INFO - preparing input from FASTA
2021-01-15 11:00:36,744 - INFO - preparing input (FASTA)
2021-01-15 11:01:08,866 - INFO - starting motif prediction (xl)
2021-01-15 11:01:08,866 - INFO - tools: MEME, BioProspector, Homer
2021-01-15 11:01:09,633 - INFO - all jobs submitted
2021-01-15 11:01:21,071 - INFO - Homer_width_6 finished, found 5 motifs
2021-01-15 11:01:30,753 - INFO - Homer_width_8 finished, found 5 motifs
2021-01-15 11:02:19,223 - INFO - Homer_width_10 finished, found 5 motifs
2021-01-15 11:03:31,532 - INFO - Homer_width_12 finished, found 5 motifs
2021-01-15 11:06:07,383 - INFO - Homer_width_14 finished, found 5 motifs
2021-01-15 11:06:07,775 - INFO - MEME_width_6 finished, found 0 motifs
2021-01-15 11:06:07,957 - INFO - MEME_width_8 finished, found 0 motifs
2021-01-15 11:06:08,127 - INFO - MEME_width_10 finished, found 0 motifs
2021-01-15 11:06:08,291 - INFO - MEME_width_12 finished, found 0 motifs
2021-01-15 11:06:08,369 - INFO - BioProspector_width_10 finished, found 5 motifs
2021-01-15 11:06:08,446 - INFO - MEME_width_14 finished, found 0 motifs
2021-01-15 11:06:08,541 - INFO - MEME_width_16 finished, found 0 motifs
2021-01-15 11:06:08,613 - INFO - MEME_width_18 finished, found 0 motifs
2021-01-15 11:06:08,720 - INFO - MEME_width_20 finished, found 0 motifs
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
2021-01-15 11:06:09,069 - INFO - using 14000 sequences
2021-01-15 11:06:13,654 - INFO - BioProspector_width_6 finished, found 5 motifs
2021-01-15 11:06:31,797 - INFO - BioProspector_width_8 finished, found 5 motifs
2021-01-15 11:06:47,815 - INFO - BioProspector_width_12 finished, found 5 motifs
2021-01-15 11:07:19,243 - INFO - BioProspector_width_16 finished, found 5 motifs
2021-01-15 11:07:32,884 - INFO - BioProspector_width_14 finished, found 5 motifs
2021-01-15 11:07:41,562 - INFO - BioProspector_width_20 finished, found 5 motifs
2021-01-15 11:08:24,047 - INFO - BioProspector_width_18 finished, found 5 motifs
2021-01-15 11:08:49,898 - INFO - Homer_width_16 finished, found 5 motifs
2021-01-15 11:15:59,385 - INFO - Homer_width_20 finished, found 5 motifs
2021-01-15 11:17:03,846 - INFO - Homer_width_18 finished, found 5 motifs
2021-01-15 11:17:44,095 - INFO - predicted 80 motifs
2021-01-15 11:17:44,116 - INFO - 80 motifs are significant
2021-01-15 11:17:44,705 - INFO - clustering 80 motifs.
2021-01-15 11:19:13,946 - INFO - creating de novo reports
2021-01-15 11:20:16,271 - INFO - finished
2021-01-15 11:20:16,271 - INFO - output dir: gimmemotifs/zone2.random_bg.debug
2021-01-15 11:20:16,271 - INFO - de novo report: gimmemotifs/zone2.random_bg.debug/gimme.denovo.html
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
2021-01-15 11:20:53,061 - INFO - creating motif scan tables
2021-01-15 11:22:06,465 - WARNING - Using 0.75-0.80
2021-01-15 11:23:27,901 - WARNING - Using 0.75-0.80
2021-01-15 11:25:30,911 - INFO - calculating stats
2021-01-15 11:26:27,389 - INFO - selecting non-redundant motifs
2021-01-15 11:26:37,981 - INFO - selected 12 non-redundant motifs: ROC AUC 0.966, PR AUC 0.927
2021-01-15 11:26:38,923 - INFO - determining FPR-based threshold
2021-01-15 11:26:40,562 - WARNING - Using 0.75-0.80
2021-01-15 11:26:41,881 - INFO - determining FPR-based threshold
2021-01-15 11:26:43,675 - WARNING - Using 0.75-0.80
2021-01-15 11:26:45,504 - WARNING - Using 0.75-0.80
2021-01-15 11:26:47,246 - WARNING - Using 0.75-0.80
2021-01-15 11:26:48,558 - INFO - determining FPR-based threshold
2021-01-15 11:26:50,237 - WARNING - Using 0.75-0.80
2021-01-15 11:26:51,566 - INFO - determining FPR-based threshold
2021-01-15 11:26:53,241 - WARNING - Using 0.75-0.80
2021-01-15 11:26:54,578 - INFO - determining FPR-based threshold
2021-01-15 11:26:56,236 - WARNING - Using 0.75-0.80
2021-01-15 11:26:57,533 - INFO - determining FPR-based threshold
2021-01-15 11:26:59,186 - WARNING - Using 0.75-0.80
2021-01-15 11:27:00,457 - INFO - determining FPR-based threshold
2021-01-15 11:27:01,994 - WARNING - Using 0.75-0.80
2021-01-15 11:27:03,671 - WARNING - Using 0.75-0.80
2021-01-15 11:27:05,012 - INFO - determining FPR-based threshold
2021-01-15 11:27:06,684 - WARNING - Using 0.75-0.80
2021-01-15 11:27:08,445 - WARNING - Using 0.75-0.80
2021-01-15 11:27:08,817 - INFO - creating statistics report
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/arraylike.py:274: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/io/formats/style.py:1268: RuntimeWarning: invalid value encountered in double_scalars
  norm = colors.Normalize(smin - (rng * low), smax + (rng * high))
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/core/arraylike.py:274: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/opt/share/FLOCAD/userspace/jtran1/miniconda3/envs/gimmemotifs/lib/python3.8/site-packages/pandas/io/formats/style.py:1268: RuntimeWarning: invalid value encountered in double_scalars
  norm = colors.Normalize(smin - (rng * low), smax + (rng * high))
2021-01-15 11:29:43,570 - INFO - gimme motifs final report: gimmemotifs/zone2.random_bg.debug/gimme.motifs.html

```

**Comment by simonvh** [comment]
Sorry for the late reply and thanks for checking! You can ignore the warnings.
