### ISSUE TITLE
I cannot install following your instructions

### ISSUE THREAD

**Issue by scovit** [vanheeringen-lab/gimmemotifs#183]
Hello,
I followed your instructions to install the software using anaconda, and I get the following error immediately after starting `gimme`:
```
Traceback (most recent call last):
  File "/Users/vscolari/opt/anaconda3/envs/gimme/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/Users/vscolari/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/Users/vscolari/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/denovo.py", line 52, in <module>
    from gimmemotifs.report import create_denovo_motif_report
  File "/Users/vscolari/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/gimmemotifs/report.py", line 19, in <module>
    from pandas.core.indexing import _non_reducing_slice
ImportError: cannot import name '_non_reducing_slice' from 'pandas.core.indexing' (/Users/vscolari/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/pandas/core/indexing.py)
```

OS MacOS Catalina: `Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

**Comment by scovit** [comment]
Golfed to:
```
% python3
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pandas.core.indexing import _non_reducing_slice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name '_non_reducing_slice' from 'pandas.core.indexing' (/Users/vscolari/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/pandas/core/indexing.py)
```

**Comment by scovit** [comment]
Deleting an old config file fixed it for me, closing this issue
