### ISSUE TITLE
Error: 127

### ISSUE THREAD

**Issue by sinnamone** [vanheeringen-lab/gimmemotifs#208]
Running this command:  

genomepy install GRCm38.p5 --annotation

I got: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spuccio/anaconda3/envs/gimme/bin/genomepy", line 8, in <module>
    sys.exit(cli())
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/genomepy/cli.py", line 262, in install
    genomepy.install_genome(
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/genomepy/functions.py", line 254, in install_genome
    provider.download_annotation(name, genomes_dir, localname=localname, **kwargs)
  File "/home/spuccio/anaconda3/envs/gimme/lib/python3.9/site-packages/genomepy/providers/base.py", line 293, in download_annotation
    raise GenomeDownloadError(
genomepy.exceptions.GenomeDownloadError: An error occured while installing the gene annotation for GRCm38.p5 from NCBI.
If you think the annotation should be there, please file a bug report at: https://github.com/vanheeringen-lab/genomepy/issues

Error: 127

**Comment by siebrenf** [comment]
I _think_ that's a file-not-found error, which should be fixed by waiting a bit (I think 17 hours will do, sorry for not noticing this earlier)
 
However, when I tried installing your gene annotation I got a different error... 
```
/home/siebrenf/.local/share/genomes/GRCm38.p5/tmpjbgo8qdj/GRCm38.p5.annotation.gff:2314111: unknown standard attribute, user defined attributes must start with a lower-case letter: SO_type
GFF3: 1 parser errors
[snip]
Error: 255
```

There seem to be some bad lines in this gene annotation! The next patch version, GRCm38.p6, has these issues fixed. If you wish to stick with GRCm38.p5, the develop branch of genomepy will skip the bad lines.
```
pip install git+https://github.com/vanheeringen-lab/genomepy.git@develop
```

**Comment by siebrenf** [comment]
PS, if you install genomepy's develop branch in a _new_ environment, you'll need to manually install the ucsc tools:

    genePredToBed
    genePredToGtf
    bedToGenePred
    gtfToGenePred
    gff3ToGenePred
using conda, these tools are prefixed with ucsc- (e.g. `ucsc-gff3ToGenePred`)
