### ISSUE TITLE
Non-redundant motif selection fails on some files

### ISSUE THREAD

**Issue by juhomon** [vanheeringen-lab/gimmemotifs#226]
**Describe the bug**
Some of my bed files produce an error when selecting non-redundant motifs for the HTML file. Weirdly this error is related to two similar sets (size, but not motif wise!) of BED files which both fail while one set doesn't. Interestingly previously with version 15.3 it was the total opposite, hence the update to 16.1. 

**To Reproduce**
At the moment I cannot provide you with the motif files or bed files, the motifs are PWMs gathered from the CISBP database and have worked previously! Below is the command with variables. 

> 
>     OUTTMP=$(echo $peaks | sed 's/.bed//') 
>     OUT="${outfolder}${OUTTMP}"
>     echo $OUT
>     mkdir -p $OUT
>     gimme motifs "${peaks}" "${OUT}" -g "${genome}" -p "${motifFile}" -N 40 --known
> 

**Error logs**
2021-11-30 15:58:44,229 - INFO - selecting non-redundant motifs
Traceback (most recent call last):
  File "/home/users/juhomon/miniconda3/envs/gimmemamba/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/home/users/juhomon/miniconda3/envs/gimmemamba/lib/python3.9/site-packages/gimmemotifs/cli.py", line 730, in cli
    args.func(args)
  File "/home/users/juhomon/miniconda3/envs/gimmemamba/lib/python3.9/site-packages/gimmemotifs/commands/motifs.py", line 246, in motifs
    nr_motifs = select_nonredundant_motifs(
  File "/home/users/juhomon/miniconda3/envs/gimmemamba/lib/python3.9/site-packages/gimmemotifs/comparison.py", line 976, in select_nonredundant_motifs
    rfe = RFE(model, i)
TypeError: __init__() takes 2 positional arguments but 3 were given

**Installation information (please complete the following information):**
 - OS: CentOS7
 - Installation: mamba -create -n gimmemamba gimmemotifs
 -  Version: v0.16.1

**Additional**
Run with SLURM

**Comment by simonvh** [comment]
Thanks for reporting this bug! It will be fixed in the next release, for now you can install the fix by running the following command in your `gimmemamba` environment:

```
pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@fix_rfe
```

**Comment by juhomon** [comment]
Amazing, thanks for the quick response! File nr1 just finished without errors, so I'll close this on my side.
