### ISSUE TITLE
error when using CIS-BP database for gimme match

### ISSUE THREAD

**Issue by lynnyummy** [vanheeringen-lab/gimmemotifs#273]
Hi, I have been running gimme motif very normally for long time, however, today when I start to use "CIS-BP" motif base, I just cannot run all the gimme motif analyses, it keeps reporting error like following,
`Fontconfig warning: ignoring UTF-8: not a valid region tag
Traceback (most recent call last):
  File "/data/home/btx541/.conda/envs/gimme/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/denovo.py", line 51, in <module>
    from gimmemotifs.stats import calc_stats, rank_motifs, write_stats
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/stats.py", line 10, in <module>
    from gimmemotifs.scanner import scan_to_best_match, Scanner
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/scanner.py", line 58, in <module>
    config = MotifConfig()
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/config.py", line 95, in __init__
    self._upgrade_config()
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/config.py", line 98, in _upgrade_config
    if "width" in self.config["params"]:
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'params'`

I am also trying to remove and reinstall gimme motifs, however, more issues come out....

Could you please help to check what issue it could be?  Thank you very much!

**Comment by simonvh** [comment]
Can you try deleting your gimmemotifs config (likely in `~/config/gimmemotifs/gimmemotifs.cfg`)?

**Comment by lynnyummy** [comment]
> Can you try deleting your gimmemotifs config (likely in `~/config/gimmemotifs/gimmemotifs.cfg`)?

Hi, I ran the command, and still having this issue..
`Traceback (most recent call last):
  File "/data/home/btx541/.conda/envs/gimme/bin/gimme", line 8, in <module>
    from gimmemotifs.cli import cli
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/denovo.py", line 51, in <module>
    from gimmemotifs.stats import calc_stats, rank_motifs, write_stats
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/stats.py", line 10, in <module>
    from gimmemotifs.scanner import scan_to_best_match, Scanner
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/scanner.py", line 58, in <module>
    config = MotifConfig()
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/config.py", line 95, in __init__
    self._upgrade_config()
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/config.py", line 98, in _upgrade_config
    if "width" in self.config["params"]:
  File "/data/home/btx541/.conda/envs/gimme/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'params'`

I am running the gimme match with default database, I don't know if it will conflict if I run another gimme match with other database e.g. JASPAR2022? maybe it is the issue?

**Comment by lynnyummy** [comment]
> Can you try deleting your gimmemotifs config (likely in `~/config/gimmemotifs/gimmemotifs.cfg`)?

Hi, yes it works, and it will be conflict if I run different motif databases at the same time, so that I need to run the money by one.

Just one question, I want to use the new JARSPAR_2022 database, however it reported `ValueError: Motif file JASPAR2022 not found`, how can I install the database?

**Comment by lynnyummy** [comment]
> Can you try deleting your gimmemotifs config (likely in `~/config/gimmemotifs/gimmemotifs.cfg`)?

yeah, it works fine! thanks!
