### ISSUE TITLE
Error in maelstrom

### ISSUE THREAD

**Issue by shaunmahony** [vanheeringen-lab/gimmemotifs#274]
I've hit an error when using maelstrom. I'm not sure where it's coming from. Here's the output:

`gimme maelstrom --no-filter --nthreads 8 -p motifs/input.pfm labeled-regs.txt hg38 maelstrom_out/out_name

2022-07-29 10:12:52,748 - INFO - Starting maelstrom
2022-07-29 10:12:53,174 - INFO - motif scanning (counts)
2022-07-29 10:12:53,174 - INFO - reading table
2022-07-29 10:13:32,374 - INFO - using 14000 sequences
2022-07-29 10:13:32,474 - INFO - Creating index for genomic GC frequencies.
2022-07-29 10:18:39,060 - INFO - setting threshold
2022-07-29 10:18:39,955 - INFO - determining FPR-based threshold
2022-07-29 10:18:51,916 - INFO - creating count table
scanning: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 200341/200341 [01:01<00:00, 3246.69 sequences/s]
2022-07-29 10:20:03,032 - INFO - done
2022-07-29 10:20:03,032 - INFO - creating dataframe
2022-07-29 10:20:09,641 - INFO - motif scanning (scores)
2022-07-29 10:20:09,641 - INFO - reading table
2022-07-29 10:20:11,138 - INFO - creating score table (z-score, GC%)
scanning: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 200341/200341 [01:32<00:00, 2159.28 sequences/s]
2022-07-29 10:26:55,599 - INFO - done
2022-07-29 10:26:55,599 - INFO - creating dataframe
2022-07-29 10:28:07,568 - INFO - Fitting MWU
/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/moap.py:322: RuntimeWarning: divide by zero encountered in log10
  self.act_ = pd.DataFrame(-np.log10(fpr.T), columns=clusters, index=df_X.columns)
2022-07-29 10:33:18,729 - INFO - Done
2022-07-29 10:33:19,584 - INFO - Fitting Hypergeom
/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/moap.py:386: RuntimeWarning: divide by zero encountered in log10
  self.act_ = pd.DataFrame(-np.log10(fpr.T), columns=clusters, index=df_X.columns)
2022-07-29 10:33:22,868 - INFO - Done
2022-07-29 10:33:25,024 - INFO - Fitting RF
2022-07-29 10:47:27,291 - INFO - Done
2022-07-29 10:47:27,328 - INFO - Rank aggregation
2022-07-29 10:47:28,984 - INFO - html report
Traceback (most recent call last):
  File "/storage/work/sam77/software/anaconda3/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/cli.py", line 746, in cli
    args.func(args)
  File "/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/commands/maelstrom.py", line 33, in maelstrom
    run_maelstrom(
  File "/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/maelstrom.py", line 546, in run_maelstrom
    maelstrom_html_report(outdir, os.path.join(outdir, "final.out.txt"), pfmfile)
  File "/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/report.py", line 923, in maelstrom_html_report
    df_styled = df_styled.wrap().render()
  File "/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/pandas/io/formats/style.py", line 344, in render
    return self._render_html(sparse_index, sparse_columns, **kwargs)
  File "/storage/work/sam77/software/anaconda3/envs/gimme/lib/python3.10/site-packages/pandas/io/formats/style_render.py", line 164, in _render_html
    d = self._translate(sparse_index, sparse_columns, max_rows, max_cols)
TypeError: ExtraStyler._translate() takes 1 positional argument but 5 were given`

**Comment by siebrenf** [comment]
What version of pandas do you have installed? @wbszhu found out that pandas 1.1.5 seems to work (in #254).

**Comment by shaunmahony** [comment]
Thank you - that solved it!
