### ISSUE TITLE
xgboost dependency

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/gimmemotifs#286]
When running gimme maelstrom (on a fresh gimme install), it will crash due to missing xgboost:

```
2022-11-29 11:54:29,527 - INFO - Starting maelstrom
2022-11-29 11:54:29,797 - INFO - Input is not mean-centered, setting the mean of all rows to 0.
2022-11-29 11:54:29,797 - INFO - Use --nocenter if you know what you're doing and want to change this behavior.
2022-11-29 11:54:29,797 - INFO - Note that if you use count data (ChIP-seq, ATAC-seq) we recommend to first transform your data, for instance using log2(), and to normalize between samples. To create a table suitable for maelstrom you can use the coverage_table script included with GimmeMotifs.
2022-11-29 11:54:31,817 - INFO - Counts, using: scANANSE/analysis/maelstrom/motif.count.txt.gz
2022-11-29 11:54:31,817 - INFO - Scores, using: scANANSE/analysis/maelstrom/motif.score.txt.gz
2022-11-29 11:55:00,524 - INFO - Selecting non-redundant motifs
2022-11-29 11:58:07,099 - INFO - Selected 238 motifs
2022-11-29 11:58:07,099 - INFO - Motifs: scANANSE/analysis/maelstrom/nonredundant.motifs.pfm
2022-11-29 11:58:07,099 - INFO - Factor mappings: scANANSE/analysis/maelstrom/nonredundant.motifs.motif2factors.txt
Traceback (most recent call last):
  File "/vol/mbconda/jsmits/gimme_dev/bin/gimme", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/gimmemotifs/scripts/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/gimmemotifs/gimmemotifs/cli.py", line 754, in cli
    exit(1)
  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/gimmemotifs/gimmemotifs/commands/maelstrom.py", line 34, in maelstrom
    run_maelstrom(
  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/gimmemotifs/gimmemotifs/maelstrom.py", line 460, in run_maelstrom
    m = Moap.create(method, ncpus=ncpus)
  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/gimmemotifs/gimmemotifs/moap.py", line 76, in create
    return cls._predictors[name.lower()](ncpus=ncpus)
  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/gimmemotifs/gimmemotifs/moap.py", line 199, in __init__
    raise ImportError("Optional dependency xgboost is required.")
ImportError: Optional dependency xgboost is required.
```
i guess it needs to be added (back?) within the gimme yaml

**Comment by siebrenf** [comment]
ah, I had missed that xgboost was used by default in maelstrom! I will change this into a message instead of an error, then users can decide to install it or skip it. (In a perfect world we would install xgboost by default, but conda was cracking with all dependencies)

you can install xgboost with `mamba install xgboost`
