### ISSUE TITLE
Maelstrom: failing during MultiTaskLasso

### ISSUE THREAD

**Issue by shaunmahony** [vanheeringen-lab/gimmemotifs#319]
Maelstrom is failing during the MultiTaskLasso step. Error produced as follows. 

```
2024-06-16 23:11:52,642 - INFO - BioProspector no longer found.
2024-06-16 23:11:52,653 - INFO - MDmodule no longer found.
2024-06-16 23:11:52,655 - INFO - Posmo no longer found.
2024-06-16 23:11:52,657 - INFO - Using included version of BioProspector.
2024-06-16 23:11:52,716 - INFO - Using included version of MDmodule.
2024-06-16 23:11:52,717 - INFO - Using included version of Posmo.
2024-06-16 23:11:52,731 - INFO - Configuration file: /storage/home/sam77/.config/gimmemotifs/gimmemotifs.cfg
2024-06-16 23:11:53,249 - INFO - Starting maelstrom
2024-06-16 23:11:53,435 - INFO - motif scanning (counts)
2024-06-16 23:11:53,435 - INFO - reading table
2024-06-16 23:12:00,664 - INFO - using 14000 sequences
2024-06-16 23:12:00,676 - INFO - Creating index for genomic GC frequencies.
2024-06-16 23:15:49,417 - INFO - setting threshold
2024-06-16 23:17:24,238 - INFO - creating count table
2024-06-16 23:22:29,762 - INFO - done
2024-06-16 23:22:29,774 - INFO - creating dataframe
2024-06-16 23:23:34,960 - INFO - motif scanning (scores)
2024-06-16 23:23:34,966 - INFO - reading table
2024-06-16 23:23:44,026 - INFO - creating score table (z-score, GC%)
2024-06-16 23:46:50,436 - INFO - done
2024-06-16 23:46:50,445 - INFO - creating dataframe
2024-06-17 00:01:38,037 - INFO - Selecting non-redundant motifs
2024-06-17 00:07:43,782 - INFO - Selected 559 motifs
2024-06-17 00:07:43,783 - INFO - Motifs: maelstrom_out/all-cisbpmotifs/nonredundant.motifs.pfm
2024-06-17 00:07:43,783 - INFO - Factor mappings: maelstrom_out/all-cisbpmotifs/nonredundant.motifs.motif2factors.txt
2024-06-17 00:07:51,287 - INFO - Fitting BayesianRidge
0it [00:00, ?it/s]
2024-06-17 00:07:53,011 - INFO - Done
2024-06-17 00:08:00,230 - INFO - Fitting XGBoostRegression
0it [00:00, ?it/s]
2024-06-17 00:08:01,946 - INFO - Done
2024-06-17 00:08:09,159 - INFO - Fitting MultiTaskLasso
2024-06-17 00:08:11,507 - WARNING - Method multitasklasso with scoring score failed
2024-06-17 00:08:11,507 - WARNING - at least one array or dtype is required
2024-06-17 00:08:11,507 - WARNING - Skipping
Traceback (most recent call last):
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/bin/gimme", line 12, in <module>
    cli(sys.argv[1:])
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/cli.py", line 755, in cli
    args.func(args)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/commands/maelstrom.py", line 42, in maelstrom
    run_maelstrom(
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/maelstrom/__init__.py", line 351, in run_maelstrom
    _moap_with_table(
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/maelstrom/__init__.py", line 452, in _moap_with_table
    moap(
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/maelstrom/moap.py", line 760, in moap
    clf.fit(motifs, df)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/gimmemotifs/maelstrom/moap.py", line 527, in fit
    model.fit(df_X, df_y)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/pipeline.py", line 476, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py", line 3212, in fit
    return super().fit(X, y, **params)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py", line 1617, in fit
    X, y = self._validate_data(
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/base.py", line 648, in _validate_data
    y = check_array(y, input_name="y", **check_y_params)
  File "/storage/home/sam77/work/software/miniconda3/envs/gimme/lib/python3.10/site-packages/sklearn/utils/validation.py", line 882, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
ValueError: at least one array or dtype is required
```

**Installation information:**
 - OS:  Linux
 - Installation conda
 - Version 0.18.0

**Additional context**
Input file is lines with the following format:
`chr17:76500201-76500401	Day0

chr14:94796951-94797151	Day0

chr2:108843948-108844148	Day0
`

**Comment by shaunmahony** [comment]
I think I solved this issue: I had spaces between the two columns, and it looks like tabs are required.
