### ISSUE TITLE
gimme motifs ... bedtools error

### ISSUE THREAD

**Issue by kopardev** [vanheeringen-lab/gimmemotifs#97]
**Describe the bug**
Motif enrichment with "gimme motifs" resulted in bedtools error:

2019-12-11 19:36:10,744 - INFO - No config found.
2019-12-11 19:36:10,744 - INFO - Creating new config.
2019-12-11 19:36:10,747 - INFO - Using included version of MDmodule.
2019-12-11 19:36:10,756 - INFO - Using system version of MEME.
2019-12-11 19:36:10,763 - INFO - Using system version of MEMEW.
2019-12-11 19:36:10,770 - INFO - Using system version of DREME.
2019-12-11 19:36:10,776 - INFO - Using system version of Weeder.
2019-12-11 19:36:10,782 - INFO - Using system version of GADEM.
2019-12-11 19:36:10,783 - INFO - Using included version of MotifSampler.
2019-12-11 19:36:10,792 - INFO - Using system version of Trawler.
2019-12-11 19:36:10,792 - INFO - Using included version of Improbizer.
2019-12-11 19:36:10,792 - INFO - Using included version of BioProspector.
2019-12-11 19:36:10,792 - INFO - Using included version of Posmo.
2019-12-11 19:36:10,793 - INFO - Using included version of ChIPMunk.
2019-12-11 19:36:10,793 - INFO - Using included version of AMD.
2019-12-11 19:36:10,793 - INFO - Using included version of HMS.
2019-12-11 19:36:10,802 - INFO - Using system version of Homer.
2019-12-11 19:36:10,808 - INFO - Using system version of XXmotif.
2019-12-11 19:36:10,816 - INFO - Using system version of ProSampler.
2019-12-11 19:36:10,817 - WARNING - Yamda not in config
2019-12-11 19:36:10,825 - INFO - Using system version of DiNAMO.
2019-12-11 19:36:10,837 - WARNING - RPMCMC not found. To include it you will have to install it.
2019-12-11 19:36:10,838 - INFO - Configuration file: /home/kopardevn/.config/gimmemotifs/gimmemotifs.cfg
2019-12-11 19:36:11,024 - INFO - creating background (matched GC%)
2019-12-11 19:36:57,722 - INFO - Creating index for genomic GC frequencies.
Traceback (most recent call last):
  File "/opt2/conda/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/cli.py", line 625, in cli
    args.func(args)
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/motifs.py", line 75, in motifs
    number=10000,
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 122, in create_background_file
    m = MatchedGcFasta(inputfile, genome, number=number, size=size)
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 548, in __init__
    matched_gc_bedfile(tmpbed, matchfile, genome, number, size=size)
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 512, in matched_gc_bedfile
    min_bin_size=min_bin_size,
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 387, in gc_bin_bedfile
    create_gc_bin_index(genome, fname, min_bin_size=min_bin_size)
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 331, in create_gc_bin_index
    fi=fasta
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/pybedtools/bedtool.py", line 345, in wrapped
    decode_output=decode_output,
  File "/opt2/conda/envs/gimme/lib/python3.6/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

	bedtools nuc -fi /data2/hg38.fasta -bed /tmp/pybedtools.77gsq__0.tmp

Error message was:
Error: malformed BED entry at line 225325. Start was greater than end. Exiting.

**To Reproduce**
gimme motifs /data2/MCF7.idr.filt.narrowPeak /data2/MCF7.idr.filt.narrowPeak_gimmemotifs --known -g /data2/hg38.fasta

**Expected behavior**
I was expecting creation of MCF7.idr.filt.narrowPeak_gimmemotifs folder with output files

**Error logs**
If applicable, add error logs to help explain your problem.

**Installation information (please complete the following information):**
 - OS: Linux, centos os
 - Installation conda inside singularity container
 - Version 0.14.0

**Additional context**

**Comment by simonvh** [comment]
Can you show line 225325 of your input file `/data2/MCF7.idr.filt.narrowPeak`? It looks like there may be an error there. Maybe peaks on chrM?

One additional tip: the input file is rather large (225,000 peaks). While this might work it will take a very long time. I suggest to take your top 5000-10,000 peaks and try running GimmeMotifs on that set. This will run much faster and usually the motif results will also be better.

**Comment by kopardev** [comment]
Thanks for your quick response. These are ATACSeq peaks. chrM has been
filtered out. The line is a chrY peak. I agree with picking top X number of
peaks, but I dont know what X will be for ATACSeq. Any suggestions?
--Vishal

**Comment by simonvh** [comment]
I don't have a good suggestion. Up to ~50,000 would be fine computationally. However, by default GimmeMotifs uses only 1,000 input regions for motif discovery. For ATACseq peaks, there could be a variety of motifs in there that are likely not all discoverable by *de novo* motif search. You can increase this 1,000 by changing the `abs_max` parameter in the config file (`~/.config/gimmemotifs/gimmemotifs.cfg`).  Keep in mind that some *de novo* motif discovery tools take very long with a large input set. The known motifs, that are included with `gimme motifs` starting with version 0.14.0, might be more informative.

**Comment by kopardev** [comment]
Thanks Simon.

I am running into different errors now .. may be you could help:

>gimme motifs /data2/MCF7.fa enrichment --known -g /index/hg38.fa -p
HOCOMOCOv11_HUMAN -b /data2/bg.fasta -s 0 -N 32
019-12-16 21:08:14,166 - INFO - skipping de novo
2019-12-16 21:08:14,167 - INFO - creating motif scan tables
2019-12-16 21:08:17,361 - INFO - using 10000 sequences
Traceback (most recent call last):
  File "/opt2/conda/envs/gimme/bin/gimme", line 11, in <module>
    cli(sys.argv[1:])
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/cli.py",
line 625, in cli
    args.func(args)
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/motifs.py",
line 174, in motifs
    gcnorm=True,
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/scanner.py",
line 306, in scan_to_file
    gcnorm=gcnorm,
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/scanner.py",
line 199, in command_scan
    genome=genome, fname=bgfile, size=fa.median_length(), gc=gcnorm
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/scanner.py",
line 752, in set_background
    cache.set(self.background_hash, (fa, gc_bins))
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/diskcache/core.py",
line 799, in set
    self._row_insert(db_key, raw, now, columns)
  File
"/opt2/conda/envs/gimme/lib/python3.6/site-packages/diskcache/core.py",
line 863, in _row_insert
    value,
sqlite3.DatabaseError: database disk image is malformed

Some jobs submitted to the cluster finish correctly. But most get this
error of "disk image is malformed" ... Any ideas?
--Vishal

**Comment by simonvh** [comment]
Ah, yes. I've run into this error when running on a cluster. The problem is that diskcache doesn't play nice with simultaneous access to the cache directory. I have been unable to fix this. The hacky workaround I've come up with is to set a job-specific cache directory.

First delete your current cache (`~/.cache/gimmemotifs/`), as it will be corrupted. Then, you can use the following snippet of code. This will set the `XDG_CACHE_HOME` variable, which will be picked up by GimmMotifs. It will also copy your current cache, to save some time on regenerating files, if they're already there.

```
NEW_CACHE=$TMPDIR/cache
mkdir -p $NEW_CACHE
if [ -z $XDG_CACHE_HOME ]; then
    XDG_CACHE_HOME=$HOME/.cache
fi
cp -r $XDG_CACHE_HOME/gimmemotifs $NEW_CACHE/
export XDG_CACHE_HOME=$NEW_CACHE
echo 'Using $XDG_CACHE_HOME for cache'
```

Hope this helps. Let me know. If it also works for you I'll add it to the FAQ.
